services:
  - type: web
    name: portfolio
    runtime: php
    buildCommand: ./build.sh
    startCommand: cp public/.htaccess . && apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://portfolio-meghana.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

databases:
  - name: portfolio-db
    plan: free
